/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCityRouteImport } from './routes/_authenticated/city'
import { Route as AuthenticatedCreatorRouteImport } from './routes/_authenticated/creator'
import { Route as AuthenticatedQuestRouteImport } from './routes/_authenticated/quest'
import { Route as AuthenticatedBriefMissionIdRouteImport } from './routes/_authenticated/brief.$missionId'
import { Route as AuthenticatedMissionMissionIdRouteImport } from './routes/_authenticated/mission.$missionId'
import { Route as AuthenticatedResultRunIdRouteImport } from './routes/_authenticated/result.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCityRoute = AuthenticatedCityRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreatorRoute = AuthenticatedCreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestRoute = AuthenticatedQuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBriefMissionIdRoute =
  AuthenticatedBriefMissionIdRouteImport.update({
    id: '/brief/$missionId',
    path: '/brief/$missionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMissionMissionIdRoute =
  AuthenticatedMissionMissionIdRouteImport.update({
    id: '/mission/$missionId',
    path: '/mission/$missionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultRunIdRoute =
  AuthenticatedResultRunIdRouteImport.update({
    id: '/result/$runId',
    path: '/result/$runId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/city': typeof AuthenticatedCityRoute
  '/creator': typeof AuthenticatedCreatorRoute
  '/quest': typeof AuthenticatedQuestRoute
  '/brief/$missionId': typeof AuthenticatedBriefMissionIdRoute
  '/mission/$missionId': typeof AuthenticatedMissionMissionIdRoute
  '/result/$runId': typeof AuthenticatedResultRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/city': typeof AuthenticatedCityRoute
  '/creator': typeof AuthenticatedCreatorRoute
  '/quest': typeof AuthenticatedQuestRoute
  '/brief/$missionId': typeof AuthenticatedBriefMissionIdRoute
  '/mission/$missionId': typeof AuthenticatedMissionMissionIdRoute
  '/result/$runId': typeof AuthenticatedResultRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/city': typeof AuthenticatedCityRoute
  '/_authenticated/creator': typeof AuthenticatedCreatorRoute
  '/_authenticated/quest': typeof AuthenticatedQuestRoute
  '/_authenticated/brief/$missionId': typeof AuthenticatedBriefMissionIdRoute
  '/_authenticated/mission/$missionId': typeof AuthenticatedMissionMissionIdRoute
  '/_authenticated/result/$runId': typeof AuthenticatedResultRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/city'
    | '/creator'
    | '/quest'
    | '/brief/$missionId'
    | '/mission/$missionId'
    | '/result/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/city'
    | '/creator'
    | '/quest'
    | '/brief/$missionId'
    | '/mission/$missionId'
    | '/result/$runId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/city'
    | '/_authenticated/creator'
    | '/_authenticated/quest'
    | '/_authenticated/brief/$missionId'
    | '/_authenticated/mission/$missionId'
    | '/_authenticated/result/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/city': {
      id: '/_authenticated/city'
      path: '/city'
      fullPath: '/city'
      preLoaderRoute: typeof AuthenticatedCityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creator': {
      id: '/_authenticated/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof AuthenticatedCreatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quest': {
      id: '/_authenticated/quest'
      path: '/quest'
      fullPath: '/quest'
      preLoaderRoute: typeof AuthenticatedQuestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brief/$missionId': {
      id: '/_authenticated/brief/$missionId'
      path: '/brief/$missionId'
      fullPath: '/brief/$missionId'
      preLoaderRoute: typeof AuthenticatedBriefMissionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mission/$missionId': {
      id: '/_authenticated/mission/$missionId'
      path: '/mission/$missionId'
      fullPath: '/mission/$missionId'
      preLoaderRoute: typeof AuthenticatedMissionMissionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/result/$runId': {
      id: '/_authenticated/result/$runId'
      path: '/result/$runId'
      fullPath: '/result/$runId'
      preLoaderRoute: typeof AuthenticatedResultRunIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCityRoute: typeof AuthenticatedCityRoute
  AuthenticatedCreatorRoute: typeof AuthenticatedCreatorRoute
  AuthenticatedQuestRoute: typeof AuthenticatedQuestRoute
  AuthenticatedBriefMissionIdRoute: typeof AuthenticatedBriefMissionIdRoute
  AuthenticatedMissionMissionIdRoute: typeof AuthenticatedMissionMissionIdRoute
  AuthenticatedResultRunIdRoute: typeof AuthenticatedResultRunIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCityRoute: AuthenticatedCityRoute,
  AuthenticatedCreatorRoute: AuthenticatedCreatorRoute,
  AuthenticatedQuestRoute: AuthenticatedQuestRoute,
  AuthenticatedBriefMissionIdRoute: AuthenticatedBriefMissionIdRoute,
  AuthenticatedMissionMissionIdRoute: AuthenticatedMissionMissionIdRoute,
  AuthenticatedResultRunIdRoute: AuthenticatedResultRunIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
