/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBriefRouteImport } from './routes/_authenticated/brief'
import { Route as AuthenticatedCityRouteImport } from './routes/_authenticated/city'
import { Route as AuthenticatedCreatorRouteImport } from './routes/_authenticated/creator'
import { Route as AuthenticatedQuestRouteImport } from './routes/_authenticated/quest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBriefRoute = AuthenticatedBriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCityRoute = AuthenticatedCityRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreatorRoute = AuthenticatedCreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestRoute = AuthenticatedQuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brief': typeof AuthenticatedBriefRoute
  '/city': typeof AuthenticatedCityRoute
  '/creator': typeof AuthenticatedCreatorRoute
  '/quest': typeof AuthenticatedQuestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brief': typeof AuthenticatedBriefRoute
  '/city': typeof AuthenticatedCityRoute
  '/creator': typeof AuthenticatedCreatorRoute
  '/quest': typeof AuthenticatedQuestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/brief': typeof AuthenticatedBriefRoute
  '/_authenticated/city': typeof AuthenticatedCityRoute
  '/_authenticated/creator': typeof AuthenticatedCreatorRoute
  '/_authenticated/quest': typeof AuthenticatedQuestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/brief' | '/city' | '/creator' | '/quest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/brief' | '/city' | '/creator' | '/quest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/brief'
    | '/_authenticated/city'
    | '/_authenticated/creator'
    | '/_authenticated/quest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/brief': {
      id: '/_authenticated/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof AuthenticatedBriefRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/city': {
      id: '/_authenticated/city'
      path: '/city'
      fullPath: '/city'
      preLoaderRoute: typeof AuthenticatedCityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creator': {
      id: '/_authenticated/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof AuthenticatedCreatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quest': {
      id: '/_authenticated/quest'
      path: '/quest'
      fullPath: '/quest'
      preLoaderRoute: typeof AuthenticatedQuestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBriefRoute: typeof AuthenticatedBriefRoute
  AuthenticatedCityRoute: typeof AuthenticatedCityRoute
  AuthenticatedCreatorRoute: typeof AuthenticatedCreatorRoute
  AuthenticatedQuestRoute: typeof AuthenticatedQuestRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBriefRoute: AuthenticatedBriefRoute,
  AuthenticatedCityRoute: AuthenticatedCityRoute,
  AuthenticatedCreatorRoute: AuthenticatedCreatorRoute,
  AuthenticatedQuestRoute: AuthenticatedQuestRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
